import 'package:app/models/log_entry.dart';

/// Creates a test [LogEntry] with sensible defaults.
/// Override any field by passing named parameters.
LogEntry makeTestEntry({
  String id = 'e1',
  String timestamp = '2026-02-07T12:00:00Z',
  String sessionId = 'sess-1',
  Severity severity = Severity.info,
  EntryKind kind = EntryKind.event,
  String? message,
  String? tag,
  ExceptionData? exception,
  String? parentId,
  String? groupId,
  String? prevId,
  String? nextId,
  WidgetPayload? widget,
  bool replace = false,
  IconRef? icon,
  Map<String, String>? labels,
  String? key,
  dynamic value,
  bool override_ = true,
  DisplayLocation display = DisplayLocation.defaultLoc,
  SessionAction? sessionAction,
  ApplicationInfo? application,
  Map<String, dynamic>? metadata,
}) {
  return LogEntry(
    id: id,
    timestamp: timestamp,
    sessionId: sessionId,
    severity: severity,
    kind: kind,
    message: message,
    tag: tag,
    exception: exception,
    parentId: parentId,
    groupId: groupId,
    prevId: prevId,
    nextId: nextId,
    widget: widget,
    replace: replace,
    icon: icon,
    labels: labels,
    key: key,
    value: value,
    override_: override_,
    display: display,
    sessionAction: sessionAction,
    application: application,
    metadata: metadata,
  );
}
