import 'package:app/models/log_entry.dart';

/// Creates a test [LogEntry] with sensible defaults.
/// Override any field by passing named parameters.
LogEntry makeTestEntry({
  String id = 'e1',
  String timestamp = '2026-02-07T12:00:00Z',
  String sessionId = 'sess-1',
  Severity severity = Severity.info,
  LogType type = LogType.text,
  String? text,
  dynamic jsonData,
  String? html,
  String? binary,
  ImageData? image,
  ExceptionData? exception,
  String? section,
  String? groupId,
  GroupAction? groupAction,
  String? groupLabel,
  bool? groupCollapsed,
  bool? sticky,
  String? stickyAction,
  String? stateKey,
  dynamic stateValue,
  SessionAction? sessionAction,
  ApplicationInfo? application,
  String? rpcId,
  RpcDirection? rpcDirection,
  String? rpcMethod,
  dynamic rpcArgs,
  dynamic rpcResponse,
  String? rpcError,
  bool? replace,
  String? customType,
  dynamic customData,
  Map<String, String>? tags,
}) {
  return LogEntry(
    id: id,
    timestamp: timestamp,
    sessionId: sessionId,
    severity: severity,
    type: type,
    text: text,
    jsonData: jsonData,
    html: html,
    binary: binary,
    image: image,
    exception: exception,
    section: section,
    groupId: groupId,
    groupAction: groupAction,
    groupLabel: groupLabel,
    groupCollapsed: groupCollapsed,
    sticky: sticky,
    stickyAction: stickyAction,
    stateKey: stateKey,
    stateValue: stateValue,
    sessionAction: sessionAction,
    application: application,
    rpcId: rpcId,
    rpcDirection: rpcDirection,
    rpcMethod: rpcMethod,
    rpcArgs: rpcArgs,
    rpcResponse: rpcResponse,
    rpcError: rpcError,
    replace: replace,
    customType: customType,
    customData: customData,
    tags: tags,
  );
}
